import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./BootstrapClient";
import AppHeader from "./AppHeader";
import AppMenu from "./AppMenu";
import { Suspense } from "react";
import { AuthContextProvider } from "@/contexts/AuthContext";
import { ColorContextProvider } from "@/contexts/ColorContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Ch07: Global State - Context Provider 적용 */}
        {/* 전역 상태 관리를 위해 Context Provider로 앱 전체를 감쌈 */}
        {/* AuthContext: 사용자 인증 정보(user, accessToken) 관리 */}
        <AuthContextProvider>
          {/* ColorContext: 색상 정보(color) 관리 */}
          <ColorContextProvider>
            <BootstrapClient/>
            <div className="d-flex flex-column vh-100">
            <AppHeader />
            <div className="flex-grow-1 container-fluid">
              <div className="row">
                <div className="col-md-4 col-lg-3 p-2">
                  {/* Ch02. Component: Streaming SSR 테스트 코드 */}
                  <Suspense fallback={<div>메뉴 로딩 중...</div>}>
                    <AppMenu />
                  </Suspense>
                </div>
                <div className="col-md-8 col-lg-9 p-2">
                  {/* Ch05. Routing: Exam02QueryString 실습 코드 */}
                  <Suspense fallback={<div>페이지 로딩 중...</div>}>
                    {children}
                  </Suspense>
                </div>
              </div>
            </div>
          </div>
          </ColorContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
